#SPDX-License-Identifier: MIT-0
---
# handlers file for vector-role
- name: restart vector
  ansible.builtin.service:
    name: vector
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
