---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  become: true
  vars:
    vector_version: "0.50.0"
    vector_clickhouse_host: "127.0.0.1"
  roles:
    - role: vector-role
